apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubectl-proxy
  name: kubectl-proxy
  namespace: monitoring
spec:
  ports:
    - port: 80
      targetPort: 8001
      name: http
    - port: 8002
      targetPort: 8002
      name: log
  selector:
    app: kubectl-proxy
