apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-proxy
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - deployments
      - statefulsets
      - replicasets
      - services
      - endpoints
      - pods
      - pods/log
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - buckets
      - gitrepositories
      - helmcharts
      - helmrepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - longhorn.io
    resources:
      - backingimagedatasources
      - backingimagemanagers
      - backingimages
      - backups
      - backuptargets
      - backupvolumes
      - engineimages
      - engines
      - instancemanagers
      - nodes
      - recurringjobs
      - replicas
      - settings
      - sharemanagers
      - volumes
    verbs:
      - get
      - list
      - watch
