apiVersion: v1
kind: ConfigMap
metadata:
  name: kubectl-proxy-openresty-config
data:
  default.conf: |-
    server {
        listen 8002;

        location / {
        proxy_pass http://127.0.0.1:8001/;

        # Reset the response's content_length, so that Lua can generate a
        # body with a different length.
        header_filter_by_lua '
            ngx.header.content_length = nil
        ';

        body_filter_by_lua '
            local ctx = ngx.ctx
            if ctx.buffers == nil then
                ctx.buffers = {}
                ctx.nbuffers = 0
            end

            local data = ngx.arg[1]
            local eof = ngx.arg[2]
            local next_idx = ctx.nbuffers + 1

            if not eof then
                if data then
                    ctx.buffers[next_idx] = data
                    ctx.nbuffers = next_idx
                    -- Send nothing to the client yet.
                    ngx.arg[1] = nil
                end
                return
            elseif data then
                ctx.buffers[next_idx] = data
                ctx.nbuffers = next_idx
            end

            -- Processing
            local rapidjson = require("rapidjson")
            body = table.concat(ctx.buffers)
            lines = {}
            for s in body:gmatch("[^\\r\\n]+") do
                table.insert(lines, s)
            end

            -- And send a new body
            ngx.arg[1] = rapidjson.encode(lines, {empty_table_as_array=true})
        ';
        }
    }
