apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubectl-proxy
  name: kubectl-proxy
spec:
  ports:
    - port: 80
      targetPort: 8001
      name: http
    - port: 8002
      targetPort: 8002
      name: log
    - port: 8003
      targetPort: 8003
      name: ext
  selector:
    app: kubectl-proxy
