apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- kubectl-proxy-clusterRoleBinding.yaml
- kubectl-proxy-clusterRole.yaml
- kubectl-proxy-deployment.yaml
- kubectl-proxy-openresty-config.yaml
- kubectl-proxy-serviceAccount.yaml
- kubectl-proxy-service.yaml
